"""Settings module schemas."""

from app.schemas.settings.configuration import (
    # Academic Reference
    AcademicCycleResponse,
    AcademicLevelResponse,
    # Subject Hours
    ApplyTemplateRequest,
    ApplyTemplateResponse,
    # Version
    BudgetVersionBase,
    BudgetVersionClone,
    BudgetVersionCreate,
    BudgetVersionResponse,
    BudgetVersionStatus,
    BudgetVersionUpdate,
    # Class Size
    ClassSizeParamBase,
    ClassSizeParamBatchEntry,
    ClassSizeParamBatchRequest,
    ClassSizeParamBatchResponse,
    ClassSizeParamBatchResponseEntry,
    ClassSizeParamCreate,
    ClassSizeParamResponse,
    ClassSizeParamUpdate,
    # Fee Structure
    FeeCategoryResponse,
    FeeStructureBase,
    FeeStructureCreate,
    FeeStructureResponse,
    FeeStructureUpdate,
    LevelInfo,
    NationalityTypeResponse,
    SubjectCreateRequest,
    SubjectHoursBase,
    SubjectHoursBatchRequest,
    SubjectHoursBatchResponse,
    SubjectHoursCreate,
    SubjectHoursEntry,
    SubjectHoursMatrixResponse,
    SubjectHoursResponse,
    SubjectHoursUpdate,
    SubjectLevelHours,
    SubjectResponse,
    SubjectWithHours,
    # System Config
    SystemConfigBase,
    SystemConfigCreate,
    SystemConfigResponse,
    SystemConfigUpdate,
    # Teacher Cost
    TeacherCategoryResponse,
    TeacherCostParamBase,
    TeacherCostParamCreate,
    TeacherCostParamResponse,
    TeacherCostParamUpdate,
    TemplateInfo,
    # Timetable
    TimetableConstraintBase,
    TimetableConstraintCreate,
    TimetableConstraintResponse,
    TimetableConstraintUpdate,
    VersionBase,
    VersionClone,
    VersionCreate,
    VersionResponse,
    VersionUpdate,
)
from app.schemas.enrollment.class_structure import (
    ClassStructureBase,
    ClassStructureBulkUpdate,
    ClassStructureCalculationRequest,
    ClassStructureCreate,
    ClassStructureResponse,
    ClassStructureUpdate,
)
from app.schemas.enrollment.distributions import (
    NationalityDistributionBase,
    NationalityDistributionBulkUpdate,
    NationalityDistributionCreate,
    NationalityDistributionResponse,
    NationalityDistributionUpdate,
)
from app.schemas.enrollment.enrollment import EnrollmentProjectionRequest
from app.schemas.enrollment.enrollment_plan import (
    EnrollmentBreakdownResponse,
    EnrollmentPlanBase,
    EnrollmentPlanCreate,
    EnrollmentPlanResponse,
    EnrollmentPlanUpdate,
    EnrollmentSummary,
    EnrollmentTotalCreate,
    EnrollmentTotalsBulkUpdate,
    EnrollmentWithDistributionResponse,
)
from app.schemas.insights.impact import (
    ImpactCalculationRequest as PlanningImpactRequest,
)
from app.schemas.insights.impact import (
    ImpactCalculationResponse as PlanningImpactResponse,
)
from app.schemas.workforce.dhg import (
    DHGHoursCalculationRequest,
    DHGSubjectHoursBase,
    DHGSubjectHoursCreate,
    DHGSubjectHoursResponse,
    DHGSubjectHoursUpdate,
    DHGTeacherRequirementBase,
    DHGTeacherRequirementCreate,
    DHGTeacherRequirementResponse,
    DHGTeacherRequirementUpdate,
    FTECalculationRequest,
    TeacherAllocationBase,
    TeacherAllocationBulkUpdate,
    TeacherAllocationCreate,
    TeacherAllocationResponse,
    TeacherAllocationUpdate,
    TRMDGapAnalysis,
    TRMDGapAnalysisResponse,
)
from app.schemas.settings.planning_progress import (
    STEP_METADATA,
    CascadeRequest,
    CascadeResponse,
    PlanningProgressResponse,
    StepBlocker,
    StepMetadata,
    StepProgress,
    StepValidation,
)

__all__ = [
    "STEP_METADATA",
    # Academic Reference
    "AcademicCycleResponse",
    "AcademicLevelResponse",
    # Subject Hours
    "ApplyTemplateRequest",
    "ApplyTemplateResponse",
    # Version
    "BudgetVersionBase",
    "BudgetVersionClone",
    "BudgetVersionCreate",
    "BudgetVersionResponse",
    "BudgetVersionStatus",
    "BudgetVersionUpdate",
    # planning_progress.py
    "CascadeRequest",
    "CascadeResponse",
    # Class Size
    "ClassSizeParamBase",
    "ClassSizeParamBatchEntry",
    "ClassSizeParamBatchRequest",
    "ClassSizeParamBatchResponse",
    "ClassSizeParamBatchResponseEntry",
    "ClassSizeParamCreate",
    "ClassSizeParamResponse",
    "ClassSizeParamUpdate",
    # planning.py
    "ClassStructureBase",
    "ClassStructureCalculationRequest",
    "ClassStructureCreate",
    "ClassStructureResponse",
    "ClassStructureUpdate",
    "ClassStructureBulkUpdate",
    "DHGHoursCalculationRequest",
    "DHGSubjectHoursBase",
    "DHGSubjectHoursCreate",
    "DHGSubjectHoursResponse",
    "DHGSubjectHoursUpdate",
    "DHGTeacherRequirementBase",
    "DHGTeacherRequirementCreate",
    "DHGTeacherRequirementResponse",
    "DHGTeacherRequirementUpdate",
    "EnrollmentBreakdownResponse",
    "EnrollmentPlanBase",
    "EnrollmentPlanCreate",
    "EnrollmentPlanResponse",
    "EnrollmentPlanUpdate",
    "EnrollmentProjectionRequest",
    "EnrollmentSummary",
    "EnrollmentTotalCreate",
    "EnrollmentTotalsBulkUpdate",
    "EnrollmentWithDistributionResponse",
    "FTECalculationRequest",
    # Fee Structure
    "FeeCategoryResponse",
    "FeeStructureBase",
    "FeeStructureCreate",
    "FeeStructureResponse",
    "FeeStructureUpdate",
    "LevelInfo",
    "NationalityDistributionBase",
    "NationalityDistributionBulkUpdate",
    "NationalityDistributionCreate",
    "NationalityDistributionResponse",
    "NationalityDistributionUpdate",
    "NationalityTypeResponse",
    "PlanningImpactRequest",
    "PlanningImpactResponse",
    "PlanningProgressResponse",
    "StepBlocker",
    "StepMetadata",
    "StepProgress",
    "StepValidation",
    "SubjectCreateRequest",
    "SubjectHoursBase",
    "SubjectHoursBatchRequest",
    "SubjectHoursBatchResponse",
    "SubjectHoursCreate",
    "SubjectHoursEntry",
    "SubjectHoursMatrixResponse",
    "SubjectHoursResponse",
    "SubjectHoursUpdate",
    "SubjectLevelHours",
    "SubjectResponse",
    "SubjectWithHours",
    # System Config
    "SystemConfigBase",
    "SystemConfigCreate",
    "SystemConfigResponse",
    "SystemConfigUpdate",
    "TRMDGapAnalysis",
    "TRMDGapAnalysisResponse",
    "TeacherAllocationBase",
    "TeacherAllocationBulkUpdate",
    "TeacherAllocationCreate",
    "TeacherAllocationResponse",
    "TeacherAllocationUpdate",
    # Teacher Cost
    "TeacherCategoryResponse",
    "TeacherCostParamBase",
    "TeacherCostParamCreate",
    "TeacherCostParamResponse",
    "TeacherCostParamUpdate",
    "TemplateInfo",
    # Timetable
    "TimetableConstraintBase",
    "TimetableConstraintCreate",
    "TimetableConstraintResponse",
    "TimetableConstraintUpdate",
    "VersionBase",
    "VersionClone",
    "VersionCreate",
    "VersionResponse",
    "VersionUpdate",
]
