/**
 * Auto-generated TypeScript types from Backend OpenAPI Specification
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is generated by running:
 *   pnpm generate:types        (requires backend running at localhost:8000)
 *   pnpm generate:types:file   (from saved openapi.json file)
 *
 * When to regenerate:
 * - After backend schema changes (new fields, type changes, enum updates)
 * - Before major releases to verify frontend-backend alignment
 * - When Zod validation errors occur in production
 *
 * How to use:
 * 1. Run type generation after backend changes
 * 2. Compare generated types with hand-written Zod schemas in api.ts
 * 3. Update Zod schemas to match any differences
 * 4. Run tests to verify schema alignment
 *
 * NOTE: This file is initially empty and will be populated when you run
 * the generate:types script with the backend server running.
 */

// Placeholder export to prevent TypeScript errors before generation
export type Placeholder = {
  _note: 'Run pnpm generate:types to populate this file'
}

// After generation, this file will contain:
// - paths: All API endpoint types
// - components: All schema types (BudgetVersion, Level, Cycle, etc.)
// - operations: All request/response types
//
// Example usage after generation:
//
// import type { components } from '@/types/generated-api'
//
// type BudgetVersion = components['schemas']['BudgetVersionResponse']
// type Level = components['schemas']['LevelResponse']
