/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated.command-center'
import { Route as AuthenticatedWorkforceIndexRouteImport } from './routes/_authenticated/workforce/index'
import { Route as AuthenticatedStrategicIndexRouteImport } from './routes/_authenticated/strategic/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRevenueIndexRouteImport } from './routes/_authenticated/revenue/index'
import { Route as AuthenticatedInvestmentsIndexRouteImport } from './routes/_authenticated/investments/index'
import { Route as AuthenticatedInsightsIndexRouteImport } from './routes/_authenticated/insights/index'
import { Route as AuthenticatedEnrollmentIndexRouteImport } from './routes/_authenticated/enrollment/index'
import { Route as AuthenticatedCostsIndexRouteImport } from './routes/_authenticated/costs/index'
import { Route as AuthenticatedConsolidationIndexRouteImport } from './routes/_authenticated/consolidation/index'
import { Route as AuthenticatedWorkforceSettingsRouteImport } from './routes/_authenticated/workforce/settings'
import { Route as AuthenticatedWorkforceSalariesRouteImport } from './routes/_authenticated/workforce/salaries'
import { Route as AuthenticatedWorkforceRequirementsRouteImport } from './routes/_authenticated/workforce/requirements'
import { Route as AuthenticatedWorkforceGapAnalysisRouteImport } from './routes/_authenticated/workforce/gap-analysis'
import { Route as AuthenticatedWorkforceEmployeesRouteImport } from './routes/_authenticated/workforce/employees'
import { Route as AuthenticatedWorkforceDhgRouteImport } from './routes/_authenticated/workforce/dhg'
import { Route as AuthenticatedWorkforceAefePositionsRouteImport } from './routes/_authenticated/workforce/aefe-positions'
import { Route as AuthenticatedStrategicTargetsRouteImport } from './routes/_authenticated/strategic/targets'
import { Route as AuthenticatedStrategicScenariosRouteImport } from './routes/_authenticated/strategic/scenarios'
import { Route as AuthenticatedStrategicLongTermRouteImport } from './routes/_authenticated/strategic/long-term'
import { Route as AuthenticatedSettingsVersionsRouteImport } from './routes/_authenticated/settings/versions'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings/system'
import { Route as AuthenticatedRevenueTuitionRouteImport } from './routes/_authenticated/revenue/tuition'
import { Route as AuthenticatedRevenueSubsidiesRouteImport } from './routes/_authenticated/revenue/subsidies'
import { Route as AuthenticatedRevenueSettingsRouteImport } from './routes/_authenticated/revenue/settings'
import { Route as AuthenticatedRevenueOtherRouteImport } from './routes/_authenticated/revenue/other'
import { Route as AuthenticatedInvestmentsSettingsRouteImport } from './routes/_authenticated/investments/settings'
import { Route as AuthenticatedInvestmentsProjectsRouteImport } from './routes/_authenticated/investments/projects'
import { Route as AuthenticatedInvestmentsCashflowRouteImport } from './routes/_authenticated/investments/cashflow'
import { Route as AuthenticatedInvestmentsCapexRouteImport } from './routes/_authenticated/investments/capex'
import { Route as AuthenticatedInsightsVarianceRouteImport } from './routes/_authenticated/insights/variance'
import { Route as AuthenticatedInsightsTrendsRouteImport } from './routes/_authenticated/insights/trends'
import { Route as AuthenticatedInsightsReportsRouteImport } from './routes/_authenticated/insights/reports'
import { Route as AuthenticatedInsightsKpisRouteImport } from './routes/_authenticated/insights/kpis'
import { Route as AuthenticatedInsightsDashboardsRouteImport } from './routes/_authenticated/insights/dashboards'
import { Route as AuthenticatedEnrollmentValidationRouteImport } from './routes/_authenticated/enrollment/validation'
import { Route as AuthenticatedEnrollmentSettingsRouteImport } from './routes/_authenticated/enrollment/settings'
import { Route as AuthenticatedEnrollmentProjectionsRouteImport } from './routes/_authenticated/enrollment/projections'
import { Route as AuthenticatedEnrollmentClassStructureRouteImport } from './routes/_authenticated/enrollment/class-structure'
import { Route as AuthenticatedCostsSettingsRouteImport } from './routes/_authenticated/costs/settings'
import { Route as AuthenticatedCostsPersonnelRouteImport } from './routes/_authenticated/costs/personnel'
import { Route as AuthenticatedCostsOverheadRouteImport } from './routes/_authenticated/costs/overhead'
import { Route as AuthenticatedCostsOperatingRouteImport } from './routes/_authenticated/costs/operating'
import { Route as AuthenticatedConsolidationStatementsRouteImport } from './routes/_authenticated/consolidation/statements'
import { Route as AuthenticatedConsolidationRollupRouteImport } from './routes/_authenticated/consolidation/rollup'
import { Route as AuthenticatedConsolidationExportsRouteImport } from './routes/_authenticated/consolidation/exports'
import { Route as AuthenticatedConsolidationChecklistRouteImport } from './routes/_authenticated/consolidation/checklist'
import { Route as AuthenticatedAdminUploadsRouteImport } from './routes/_authenticated/admin/uploads'
import { Route as AuthenticatedAdminHistoricalImportRouteImport } from './routes/_authenticated/admin/historical-import'
import { Route as AuthenticatedWorkforceSettingsTimetableRouteImport } from './routes/_authenticated/workforce/settings/timetable'
import { Route as AuthenticatedWorkforceSettingsSubjectHoursRouteImport } from './routes/_authenticated/workforce/settings/subject-hours'
import { Route as AuthenticatedWorkforceSettingsHsaRatesRouteImport } from './routes/_authenticated/workforce/settings/hsa-rates'
import { Route as AuthenticatedWorkforceSettingsCostParametersRouteImport } from './routes/_authenticated/workforce/settings/cost-parameters'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkforceIndexRoute =
  AuthenticatedWorkforceIndexRouteImport.update({
    id: '/workforce/',
    path: '/workforce/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStrategicIndexRoute =
  AuthenticatedStrategicIndexRouteImport.update({
    id: '/strategic/',
    path: '/strategic/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRevenueIndexRoute =
  AuthenticatedRevenueIndexRouteImport.update({
    id: '/revenue/',
    path: '/revenue/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvestmentsIndexRoute =
  AuthenticatedInvestmentsIndexRouteImport.update({
    id: '/investments/',
    path: '/investments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsIndexRoute =
  AuthenticatedInsightsIndexRouteImport.update({
    id: '/insights/',
    path: '/insights/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEnrollmentIndexRoute =
  AuthenticatedEnrollmentIndexRouteImport.update({
    id: '/enrollment/',
    path: '/enrollment/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCostsIndexRoute = AuthenticatedCostsIndexRouteImport.update({
  id: '/costs/',
  path: '/costs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsolidationIndexRoute =
  AuthenticatedConsolidationIndexRouteImport.update({
    id: '/consolidation/',
    path: '/consolidation/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkforceSettingsRoute =
  AuthenticatedWorkforceSettingsRouteImport.update({
    id: '/workforce/settings',
    path: '/workforce/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkforceSalariesRoute =
  AuthenticatedWorkforceSalariesRouteImport.update({
    id: '/workforce/salaries',
    path: '/workforce/salaries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkforceRequirementsRoute =
  AuthenticatedWorkforceRequirementsRouteImport.update({
    id: '/workforce/requirements',
    path: '/workforce/requirements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkforceGapAnalysisRoute =
  AuthenticatedWorkforceGapAnalysisRouteImport.update({
    id: '/workforce/gap-analysis',
    path: '/workforce/gap-analysis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkforceEmployeesRoute =
  AuthenticatedWorkforceEmployeesRouteImport.update({
    id: '/workforce/employees',
    path: '/workforce/employees',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkforceDhgRoute =
  AuthenticatedWorkforceDhgRouteImport.update({
    id: '/workforce/dhg',
    path: '/workforce/dhg',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkforceAefePositionsRoute =
  AuthenticatedWorkforceAefePositionsRouteImport.update({
    id: '/workforce/aefe-positions',
    path: '/workforce/aefe-positions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStrategicTargetsRoute =
  AuthenticatedStrategicTargetsRouteImport.update({
    id: '/strategic/targets',
    path: '/strategic/targets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStrategicScenariosRoute =
  AuthenticatedStrategicScenariosRouteImport.update({
    id: '/strategic/scenarios',
    path: '/strategic/scenarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStrategicLongTermRoute =
  AuthenticatedStrategicLongTermRouteImport.update({
    id: '/strategic/long-term',
    path: '/strategic/long-term',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsVersionsRoute =
  AuthenticatedSettingsVersionsRouteImport.update({
    id: '/settings/versions',
    path: '/settings/versions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/settings/system',
    path: '/settings/system',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRevenueTuitionRoute =
  AuthenticatedRevenueTuitionRouteImport.update({
    id: '/revenue/tuition',
    path: '/revenue/tuition',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRevenueSubsidiesRoute =
  AuthenticatedRevenueSubsidiesRouteImport.update({
    id: '/revenue/subsidies',
    path: '/revenue/subsidies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRevenueSettingsRoute =
  AuthenticatedRevenueSettingsRouteImport.update({
    id: '/revenue/settings',
    path: '/revenue/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRevenueOtherRoute =
  AuthenticatedRevenueOtherRouteImport.update({
    id: '/revenue/other',
    path: '/revenue/other',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvestmentsSettingsRoute =
  AuthenticatedInvestmentsSettingsRouteImport.update({
    id: '/investments/settings',
    path: '/investments/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvestmentsProjectsRoute =
  AuthenticatedInvestmentsProjectsRouteImport.update({
    id: '/investments/projects',
    path: '/investments/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvestmentsCashflowRoute =
  AuthenticatedInvestmentsCashflowRouteImport.update({
    id: '/investments/cashflow',
    path: '/investments/cashflow',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvestmentsCapexRoute =
  AuthenticatedInvestmentsCapexRouteImport.update({
    id: '/investments/capex',
    path: '/investments/capex',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsVarianceRoute =
  AuthenticatedInsightsVarianceRouteImport.update({
    id: '/insights/variance',
    path: '/insights/variance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsTrendsRoute =
  AuthenticatedInsightsTrendsRouteImport.update({
    id: '/insights/trends',
    path: '/insights/trends',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsReportsRoute =
  AuthenticatedInsightsReportsRouteImport.update({
    id: '/insights/reports',
    path: '/insights/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsKpisRoute =
  AuthenticatedInsightsKpisRouteImport.update({
    id: '/insights/kpis',
    path: '/insights/kpis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsDashboardsRoute =
  AuthenticatedInsightsDashboardsRouteImport.update({
    id: '/insights/dashboards',
    path: '/insights/dashboards',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEnrollmentValidationRoute =
  AuthenticatedEnrollmentValidationRouteImport.update({
    id: '/enrollment/validation',
    path: '/enrollment/validation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEnrollmentSettingsRoute =
  AuthenticatedEnrollmentSettingsRouteImport.update({
    id: '/enrollment/settings',
    path: '/enrollment/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEnrollmentProjectionsRoute =
  AuthenticatedEnrollmentProjectionsRouteImport.update({
    id: '/enrollment/projections',
    path: '/enrollment/projections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEnrollmentClassStructureRoute =
  AuthenticatedEnrollmentClassStructureRouteImport.update({
    id: '/enrollment/class-structure',
    path: '/enrollment/class-structure',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCostsSettingsRoute =
  AuthenticatedCostsSettingsRouteImport.update({
    id: '/costs/settings',
    path: '/costs/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCostsPersonnelRoute =
  AuthenticatedCostsPersonnelRouteImport.update({
    id: '/costs/personnel',
    path: '/costs/personnel',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCostsOverheadRoute =
  AuthenticatedCostsOverheadRouteImport.update({
    id: '/costs/overhead',
    path: '/costs/overhead',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCostsOperatingRoute =
  AuthenticatedCostsOperatingRouteImport.update({
    id: '/costs/operating',
    path: '/costs/operating',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsolidationStatementsRoute =
  AuthenticatedConsolidationStatementsRouteImport.update({
    id: '/consolidation/statements',
    path: '/consolidation/statements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsolidationRollupRoute =
  AuthenticatedConsolidationRollupRouteImport.update({
    id: '/consolidation/rollup',
    path: '/consolidation/rollup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsolidationExportsRoute =
  AuthenticatedConsolidationExportsRouteImport.update({
    id: '/consolidation/exports',
    path: '/consolidation/exports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsolidationChecklistRoute =
  AuthenticatedConsolidationChecklistRouteImport.update({
    id: '/consolidation/checklist',
    path: '/consolidation/checklist',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUploadsRoute =
  AuthenticatedAdminUploadsRouteImport.update({
    id: '/admin/uploads',
    path: '/admin/uploads',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminHistoricalImportRoute =
  AuthenticatedAdminHistoricalImportRouteImport.update({
    id: '/admin/historical-import',
    path: '/admin/historical-import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkforceSettingsTimetableRoute =
  AuthenticatedWorkforceSettingsTimetableRouteImport.update({
    id: '/timetable',
    path: '/timetable',
    getParentRoute: () => AuthenticatedWorkforceSettingsRoute,
  } as any)
const AuthenticatedWorkforceSettingsSubjectHoursRoute =
  AuthenticatedWorkforceSettingsSubjectHoursRouteImport.update({
    id: '/subject-hours',
    path: '/subject-hours',
    getParentRoute: () => AuthenticatedWorkforceSettingsRoute,
  } as any)
const AuthenticatedWorkforceSettingsHsaRatesRoute =
  AuthenticatedWorkforceSettingsHsaRatesRouteImport.update({
    id: '/hsa-rates',
    path: '/hsa-rates',
    getParentRoute: () => AuthenticatedWorkforceSettingsRoute,
  } as any)
const AuthenticatedWorkforceSettingsCostParametersRoute =
  AuthenticatedWorkforceSettingsCostParametersRouteImport.update({
    id: '/cost-parameters',
    path: '/cost-parameters',
    getParentRoute: () => AuthenticatedWorkforceSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/historical-import': typeof AuthenticatedAdminHistoricalImportRoute
  '/admin/uploads': typeof AuthenticatedAdminUploadsRoute
  '/consolidation/checklist': typeof AuthenticatedConsolidationChecklistRoute
  '/consolidation/exports': typeof AuthenticatedConsolidationExportsRoute
  '/consolidation/rollup': typeof AuthenticatedConsolidationRollupRoute
  '/consolidation/statements': typeof AuthenticatedConsolidationStatementsRoute
  '/costs/operating': typeof AuthenticatedCostsOperatingRoute
  '/costs/overhead': typeof AuthenticatedCostsOverheadRoute
  '/costs/personnel': typeof AuthenticatedCostsPersonnelRoute
  '/costs/settings': typeof AuthenticatedCostsSettingsRoute
  '/enrollment/class-structure': typeof AuthenticatedEnrollmentClassStructureRoute
  '/enrollment/projections': typeof AuthenticatedEnrollmentProjectionsRoute
  '/enrollment/settings': typeof AuthenticatedEnrollmentSettingsRoute
  '/enrollment/validation': typeof AuthenticatedEnrollmentValidationRoute
  '/insights/dashboards': typeof AuthenticatedInsightsDashboardsRoute
  '/insights/kpis': typeof AuthenticatedInsightsKpisRoute
  '/insights/reports': typeof AuthenticatedInsightsReportsRoute
  '/insights/trends': typeof AuthenticatedInsightsTrendsRoute
  '/insights/variance': typeof AuthenticatedInsightsVarianceRoute
  '/investments/capex': typeof AuthenticatedInvestmentsCapexRoute
  '/investments/cashflow': typeof AuthenticatedInvestmentsCashflowRoute
  '/investments/projects': typeof AuthenticatedInvestmentsProjectsRoute
  '/investments/settings': typeof AuthenticatedInvestmentsSettingsRoute
  '/revenue/other': typeof AuthenticatedRevenueOtherRoute
  '/revenue/settings': typeof AuthenticatedRevenueSettingsRoute
  '/revenue/subsidies': typeof AuthenticatedRevenueSubsidiesRoute
  '/revenue/tuition': typeof AuthenticatedRevenueTuitionRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/versions': typeof AuthenticatedSettingsVersionsRoute
  '/strategic/long-term': typeof AuthenticatedStrategicLongTermRoute
  '/strategic/scenarios': typeof AuthenticatedStrategicScenariosRoute
  '/strategic/targets': typeof AuthenticatedStrategicTargetsRoute
  '/workforce/aefe-positions': typeof AuthenticatedWorkforceAefePositionsRoute
  '/workforce/dhg': typeof AuthenticatedWorkforceDhgRoute
  '/workforce/employees': typeof AuthenticatedWorkforceEmployeesRoute
  '/workforce/gap-analysis': typeof AuthenticatedWorkforceGapAnalysisRoute
  '/workforce/requirements': typeof AuthenticatedWorkforceRequirementsRoute
  '/workforce/salaries': typeof AuthenticatedWorkforceSalariesRoute
  '/workforce/settings': typeof AuthenticatedWorkforceSettingsRouteWithChildren
  '/consolidation': typeof AuthenticatedConsolidationIndexRoute
  '/costs': typeof AuthenticatedCostsIndexRoute
  '/enrollment': typeof AuthenticatedEnrollmentIndexRoute
  '/insights': typeof AuthenticatedInsightsIndexRoute
  '/investments': typeof AuthenticatedInvestmentsIndexRoute
  '/revenue': typeof AuthenticatedRevenueIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/strategic': typeof AuthenticatedStrategicIndexRoute
  '/workforce': typeof AuthenticatedWorkforceIndexRoute
  '/workforce/settings/cost-parameters': typeof AuthenticatedWorkforceSettingsCostParametersRoute
  '/workforce/settings/hsa-rates': typeof AuthenticatedWorkforceSettingsHsaRatesRoute
  '/workforce/settings/subject-hours': typeof AuthenticatedWorkforceSettingsSubjectHoursRoute
  '/workforce/settings/timetable': typeof AuthenticatedWorkforceSettingsTimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/historical-import': typeof AuthenticatedAdminHistoricalImportRoute
  '/admin/uploads': typeof AuthenticatedAdminUploadsRoute
  '/consolidation/checklist': typeof AuthenticatedConsolidationChecklistRoute
  '/consolidation/exports': typeof AuthenticatedConsolidationExportsRoute
  '/consolidation/rollup': typeof AuthenticatedConsolidationRollupRoute
  '/consolidation/statements': typeof AuthenticatedConsolidationStatementsRoute
  '/costs/operating': typeof AuthenticatedCostsOperatingRoute
  '/costs/overhead': typeof AuthenticatedCostsOverheadRoute
  '/costs/personnel': typeof AuthenticatedCostsPersonnelRoute
  '/costs/settings': typeof AuthenticatedCostsSettingsRoute
  '/enrollment/class-structure': typeof AuthenticatedEnrollmentClassStructureRoute
  '/enrollment/projections': typeof AuthenticatedEnrollmentProjectionsRoute
  '/enrollment/settings': typeof AuthenticatedEnrollmentSettingsRoute
  '/enrollment/validation': typeof AuthenticatedEnrollmentValidationRoute
  '/insights/dashboards': typeof AuthenticatedInsightsDashboardsRoute
  '/insights/kpis': typeof AuthenticatedInsightsKpisRoute
  '/insights/reports': typeof AuthenticatedInsightsReportsRoute
  '/insights/trends': typeof AuthenticatedInsightsTrendsRoute
  '/insights/variance': typeof AuthenticatedInsightsVarianceRoute
  '/investments/capex': typeof AuthenticatedInvestmentsCapexRoute
  '/investments/cashflow': typeof AuthenticatedInvestmentsCashflowRoute
  '/investments/projects': typeof AuthenticatedInvestmentsProjectsRoute
  '/investments/settings': typeof AuthenticatedInvestmentsSettingsRoute
  '/revenue/other': typeof AuthenticatedRevenueOtherRoute
  '/revenue/settings': typeof AuthenticatedRevenueSettingsRoute
  '/revenue/subsidies': typeof AuthenticatedRevenueSubsidiesRoute
  '/revenue/tuition': typeof AuthenticatedRevenueTuitionRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/versions': typeof AuthenticatedSettingsVersionsRoute
  '/strategic/long-term': typeof AuthenticatedStrategicLongTermRoute
  '/strategic/scenarios': typeof AuthenticatedStrategicScenariosRoute
  '/strategic/targets': typeof AuthenticatedStrategicTargetsRoute
  '/workforce/aefe-positions': typeof AuthenticatedWorkforceAefePositionsRoute
  '/workforce/dhg': typeof AuthenticatedWorkforceDhgRoute
  '/workforce/employees': typeof AuthenticatedWorkforceEmployeesRoute
  '/workforce/gap-analysis': typeof AuthenticatedWorkforceGapAnalysisRoute
  '/workforce/requirements': typeof AuthenticatedWorkforceRequirementsRoute
  '/workforce/salaries': typeof AuthenticatedWorkforceSalariesRoute
  '/workforce/settings': typeof AuthenticatedWorkforceSettingsRouteWithChildren
  '/consolidation': typeof AuthenticatedConsolidationIndexRoute
  '/costs': typeof AuthenticatedCostsIndexRoute
  '/enrollment': typeof AuthenticatedEnrollmentIndexRoute
  '/insights': typeof AuthenticatedInsightsIndexRoute
  '/investments': typeof AuthenticatedInvestmentsIndexRoute
  '/revenue': typeof AuthenticatedRevenueIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/strategic': typeof AuthenticatedStrategicIndexRoute
  '/workforce': typeof AuthenticatedWorkforceIndexRoute
  '/workforce/settings/cost-parameters': typeof AuthenticatedWorkforceSettingsCostParametersRoute
  '/workforce/settings/hsa-rates': typeof AuthenticatedWorkforceSettingsHsaRatesRoute
  '/workforce/settings/subject-hours': typeof AuthenticatedWorkforceSettingsSubjectHoursRoute
  '/workforce/settings/timetable': typeof AuthenticatedWorkforceSettingsTimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/historical-import': typeof AuthenticatedAdminHistoricalImportRoute
  '/_authenticated/admin/uploads': typeof AuthenticatedAdminUploadsRoute
  '/_authenticated/consolidation/checklist': typeof AuthenticatedConsolidationChecklistRoute
  '/_authenticated/consolidation/exports': typeof AuthenticatedConsolidationExportsRoute
  '/_authenticated/consolidation/rollup': typeof AuthenticatedConsolidationRollupRoute
  '/_authenticated/consolidation/statements': typeof AuthenticatedConsolidationStatementsRoute
  '/_authenticated/costs/operating': typeof AuthenticatedCostsOperatingRoute
  '/_authenticated/costs/overhead': typeof AuthenticatedCostsOverheadRoute
  '/_authenticated/costs/personnel': typeof AuthenticatedCostsPersonnelRoute
  '/_authenticated/costs/settings': typeof AuthenticatedCostsSettingsRoute
  '/_authenticated/enrollment/class-structure': typeof AuthenticatedEnrollmentClassStructureRoute
  '/_authenticated/enrollment/projections': typeof AuthenticatedEnrollmentProjectionsRoute
  '/_authenticated/enrollment/settings': typeof AuthenticatedEnrollmentSettingsRoute
  '/_authenticated/enrollment/validation': typeof AuthenticatedEnrollmentValidationRoute
  '/_authenticated/insights/dashboards': typeof AuthenticatedInsightsDashboardsRoute
  '/_authenticated/insights/kpis': typeof AuthenticatedInsightsKpisRoute
  '/_authenticated/insights/reports': typeof AuthenticatedInsightsReportsRoute
  '/_authenticated/insights/trends': typeof AuthenticatedInsightsTrendsRoute
  '/_authenticated/insights/variance': typeof AuthenticatedInsightsVarianceRoute
  '/_authenticated/investments/capex': typeof AuthenticatedInvestmentsCapexRoute
  '/_authenticated/investments/cashflow': typeof AuthenticatedInvestmentsCashflowRoute
  '/_authenticated/investments/projects': typeof AuthenticatedInvestmentsProjectsRoute
  '/_authenticated/investments/settings': typeof AuthenticatedInvestmentsSettingsRoute
  '/_authenticated/revenue/other': typeof AuthenticatedRevenueOtherRoute
  '/_authenticated/revenue/settings': typeof AuthenticatedRevenueSettingsRoute
  '/_authenticated/revenue/subsidies': typeof AuthenticatedRevenueSubsidiesRoute
  '/_authenticated/revenue/tuition': typeof AuthenticatedRevenueTuitionRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/settings/versions': typeof AuthenticatedSettingsVersionsRoute
  '/_authenticated/strategic/long-term': typeof AuthenticatedStrategicLongTermRoute
  '/_authenticated/strategic/scenarios': typeof AuthenticatedStrategicScenariosRoute
  '/_authenticated/strategic/targets': typeof AuthenticatedStrategicTargetsRoute
  '/_authenticated/workforce/aefe-positions': typeof AuthenticatedWorkforceAefePositionsRoute
  '/_authenticated/workforce/dhg': typeof AuthenticatedWorkforceDhgRoute
  '/_authenticated/workforce/employees': typeof AuthenticatedWorkforceEmployeesRoute
  '/_authenticated/workforce/gap-analysis': typeof AuthenticatedWorkforceGapAnalysisRoute
  '/_authenticated/workforce/requirements': typeof AuthenticatedWorkforceRequirementsRoute
  '/_authenticated/workforce/salaries': typeof AuthenticatedWorkforceSalariesRoute
  '/_authenticated/workforce/settings': typeof AuthenticatedWorkforceSettingsRouteWithChildren
  '/_authenticated/consolidation/': typeof AuthenticatedConsolidationIndexRoute
  '/_authenticated/costs/': typeof AuthenticatedCostsIndexRoute
  '/_authenticated/enrollment/': typeof AuthenticatedEnrollmentIndexRoute
  '/_authenticated/insights/': typeof AuthenticatedInsightsIndexRoute
  '/_authenticated/investments/': typeof AuthenticatedInvestmentsIndexRoute
  '/_authenticated/revenue/': typeof AuthenticatedRevenueIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/strategic/': typeof AuthenticatedStrategicIndexRoute
  '/_authenticated/workforce/': typeof AuthenticatedWorkforceIndexRoute
  '/_authenticated/workforce/settings/cost-parameters': typeof AuthenticatedWorkforceSettingsCostParametersRoute
  '/_authenticated/workforce/settings/hsa-rates': typeof AuthenticatedWorkforceSettingsHsaRatesRoute
  '/_authenticated/workforce/settings/subject-hours': typeof AuthenticatedWorkforceSettingsSubjectHoursRoute
  '/_authenticated/workforce/settings/timetable': typeof AuthenticatedWorkforceSettingsTimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/command-center'
    | '/dashboard'
    | '/admin/historical-import'
    | '/admin/uploads'
    | '/consolidation/checklist'
    | '/consolidation/exports'
    | '/consolidation/rollup'
    | '/consolidation/statements'
    | '/costs/operating'
    | '/costs/overhead'
    | '/costs/personnel'
    | '/costs/settings'
    | '/enrollment/class-structure'
    | '/enrollment/projections'
    | '/enrollment/settings'
    | '/enrollment/validation'
    | '/insights/dashboards'
    | '/insights/kpis'
    | '/insights/reports'
    | '/insights/trends'
    | '/insights/variance'
    | '/investments/capex'
    | '/investments/cashflow'
    | '/investments/projects'
    | '/investments/settings'
    | '/revenue/other'
    | '/revenue/settings'
    | '/revenue/subsidies'
    | '/revenue/tuition'
    | '/settings/system'
    | '/settings/versions'
    | '/strategic/long-term'
    | '/strategic/scenarios'
    | '/strategic/targets'
    | '/workforce/aefe-positions'
    | '/workforce/dhg'
    | '/workforce/employees'
    | '/workforce/gap-analysis'
    | '/workforce/requirements'
    | '/workforce/salaries'
    | '/workforce/settings'
    | '/consolidation'
    | '/costs'
    | '/enrollment'
    | '/insights'
    | '/investments'
    | '/revenue'
    | '/settings'
    | '/strategic'
    | '/workforce'
    | '/workforce/settings/cost-parameters'
    | '/workforce/settings/hsa-rates'
    | '/workforce/settings/subject-hours'
    | '/workforce/settings/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/command-center'
    | '/dashboard'
    | '/admin/historical-import'
    | '/admin/uploads'
    | '/consolidation/checklist'
    | '/consolidation/exports'
    | '/consolidation/rollup'
    | '/consolidation/statements'
    | '/costs/operating'
    | '/costs/overhead'
    | '/costs/personnel'
    | '/costs/settings'
    | '/enrollment/class-structure'
    | '/enrollment/projections'
    | '/enrollment/settings'
    | '/enrollment/validation'
    | '/insights/dashboards'
    | '/insights/kpis'
    | '/insights/reports'
    | '/insights/trends'
    | '/insights/variance'
    | '/investments/capex'
    | '/investments/cashflow'
    | '/investments/projects'
    | '/investments/settings'
    | '/revenue/other'
    | '/revenue/settings'
    | '/revenue/subsidies'
    | '/revenue/tuition'
    | '/settings/system'
    | '/settings/versions'
    | '/strategic/long-term'
    | '/strategic/scenarios'
    | '/strategic/targets'
    | '/workforce/aefe-positions'
    | '/workforce/dhg'
    | '/workforce/employees'
    | '/workforce/gap-analysis'
    | '/workforce/requirements'
    | '/workforce/salaries'
    | '/workforce/settings'
    | '/consolidation'
    | '/costs'
    | '/enrollment'
    | '/insights'
    | '/investments'
    | '/revenue'
    | '/settings'
    | '/strategic'
    | '/workforce'
    | '/workforce/settings/cost-parameters'
    | '/workforce/settings/hsa-rates'
    | '/workforce/settings/subject-hours'
    | '/workforce/settings/timetable'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/demo'
    | '/login'
    | '/_authenticated/command-center'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/historical-import'
    | '/_authenticated/admin/uploads'
    | '/_authenticated/consolidation/checklist'
    | '/_authenticated/consolidation/exports'
    | '/_authenticated/consolidation/rollup'
    | '/_authenticated/consolidation/statements'
    | '/_authenticated/costs/operating'
    | '/_authenticated/costs/overhead'
    | '/_authenticated/costs/personnel'
    | '/_authenticated/costs/settings'
    | '/_authenticated/enrollment/class-structure'
    | '/_authenticated/enrollment/projections'
    | '/_authenticated/enrollment/settings'
    | '/_authenticated/enrollment/validation'
    | '/_authenticated/insights/dashboards'
    | '/_authenticated/insights/kpis'
    | '/_authenticated/insights/reports'
    | '/_authenticated/insights/trends'
    | '/_authenticated/insights/variance'
    | '/_authenticated/investments/capex'
    | '/_authenticated/investments/cashflow'
    | '/_authenticated/investments/projects'
    | '/_authenticated/investments/settings'
    | '/_authenticated/revenue/other'
    | '/_authenticated/revenue/settings'
    | '/_authenticated/revenue/subsidies'
    | '/_authenticated/revenue/tuition'
    | '/_authenticated/settings/system'
    | '/_authenticated/settings/versions'
    | '/_authenticated/strategic/long-term'
    | '/_authenticated/strategic/scenarios'
    | '/_authenticated/strategic/targets'
    | '/_authenticated/workforce/aefe-positions'
    | '/_authenticated/workforce/dhg'
    | '/_authenticated/workforce/employees'
    | '/_authenticated/workforce/gap-analysis'
    | '/_authenticated/workforce/requirements'
    | '/_authenticated/workforce/salaries'
    | '/_authenticated/workforce/settings'
    | '/_authenticated/consolidation/'
    | '/_authenticated/costs/'
    | '/_authenticated/enrollment/'
    | '/_authenticated/insights/'
    | '/_authenticated/investments/'
    | '/_authenticated/revenue/'
    | '/_authenticated/settings/'
    | '/_authenticated/strategic/'
    | '/_authenticated/workforce/'
    | '/_authenticated/workforce/settings/cost-parameters'
    | '/_authenticated/workforce/settings/hsa-rates'
    | '/_authenticated/workforce/settings/subject-hours'
    | '/_authenticated/workforce/settings/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workforce/': {
      id: '/_authenticated/workforce/'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof AuthenticatedWorkforceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/strategic/': {
      id: '/_authenticated/strategic/'
      path: '/strategic'
      fullPath: '/strategic'
      preLoaderRoute: typeof AuthenticatedStrategicIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenue/': {
      id: '/_authenticated/revenue/'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investments/': {
      id: '/_authenticated/investments/'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AuthenticatedInvestmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights/': {
      id: '/_authenticated/insights/'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/enrollment/': {
      id: '/_authenticated/enrollment/'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof AuthenticatedEnrollmentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs/': {
      id: '/_authenticated/costs/'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consolidation/': {
      id: '/_authenticated/consolidation/'
      path: '/consolidation'
      fullPath: '/consolidation'
      preLoaderRoute: typeof AuthenticatedConsolidationIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workforce/settings': {
      id: '/_authenticated/workforce/settings'
      path: '/workforce/settings'
      fullPath: '/workforce/settings'
      preLoaderRoute: typeof AuthenticatedWorkforceSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workforce/salaries': {
      id: '/_authenticated/workforce/salaries'
      path: '/workforce/salaries'
      fullPath: '/workforce/salaries'
      preLoaderRoute: typeof AuthenticatedWorkforceSalariesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workforce/requirements': {
      id: '/_authenticated/workforce/requirements'
      path: '/workforce/requirements'
      fullPath: '/workforce/requirements'
      preLoaderRoute: typeof AuthenticatedWorkforceRequirementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workforce/gap-analysis': {
      id: '/_authenticated/workforce/gap-analysis'
      path: '/workforce/gap-analysis'
      fullPath: '/workforce/gap-analysis'
      preLoaderRoute: typeof AuthenticatedWorkforceGapAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workforce/employees': {
      id: '/_authenticated/workforce/employees'
      path: '/workforce/employees'
      fullPath: '/workforce/employees'
      preLoaderRoute: typeof AuthenticatedWorkforceEmployeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workforce/dhg': {
      id: '/_authenticated/workforce/dhg'
      path: '/workforce/dhg'
      fullPath: '/workforce/dhg'
      preLoaderRoute: typeof AuthenticatedWorkforceDhgRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workforce/aefe-positions': {
      id: '/_authenticated/workforce/aefe-positions'
      path: '/workforce/aefe-positions'
      fullPath: '/workforce/aefe-positions'
      preLoaderRoute: typeof AuthenticatedWorkforceAefePositionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/strategic/targets': {
      id: '/_authenticated/strategic/targets'
      path: '/strategic/targets'
      fullPath: '/strategic/targets'
      preLoaderRoute: typeof AuthenticatedStrategicTargetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/strategic/scenarios': {
      id: '/_authenticated/strategic/scenarios'
      path: '/strategic/scenarios'
      fullPath: '/strategic/scenarios'
      preLoaderRoute: typeof AuthenticatedStrategicScenariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/strategic/long-term': {
      id: '/_authenticated/strategic/long-term'
      path: '/strategic/long-term'
      fullPath: '/strategic/long-term'
      preLoaderRoute: typeof AuthenticatedStrategicLongTermRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/versions': {
      id: '/_authenticated/settings/versions'
      path: '/settings/versions'
      fullPath: '/settings/versions'
      preLoaderRoute: typeof AuthenticatedSettingsVersionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenue/tuition': {
      id: '/_authenticated/revenue/tuition'
      path: '/revenue/tuition'
      fullPath: '/revenue/tuition'
      preLoaderRoute: typeof AuthenticatedRevenueTuitionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenue/subsidies': {
      id: '/_authenticated/revenue/subsidies'
      path: '/revenue/subsidies'
      fullPath: '/revenue/subsidies'
      preLoaderRoute: typeof AuthenticatedRevenueSubsidiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenue/settings': {
      id: '/_authenticated/revenue/settings'
      path: '/revenue/settings'
      fullPath: '/revenue/settings'
      preLoaderRoute: typeof AuthenticatedRevenueSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenue/other': {
      id: '/_authenticated/revenue/other'
      path: '/revenue/other'
      fullPath: '/revenue/other'
      preLoaderRoute: typeof AuthenticatedRevenueOtherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investments/settings': {
      id: '/_authenticated/investments/settings'
      path: '/investments/settings'
      fullPath: '/investments/settings'
      preLoaderRoute: typeof AuthenticatedInvestmentsSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investments/projects': {
      id: '/_authenticated/investments/projects'
      path: '/investments/projects'
      fullPath: '/investments/projects'
      preLoaderRoute: typeof AuthenticatedInvestmentsProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investments/cashflow': {
      id: '/_authenticated/investments/cashflow'
      path: '/investments/cashflow'
      fullPath: '/investments/cashflow'
      preLoaderRoute: typeof AuthenticatedInvestmentsCashflowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investments/capex': {
      id: '/_authenticated/investments/capex'
      path: '/investments/capex'
      fullPath: '/investments/capex'
      preLoaderRoute: typeof AuthenticatedInvestmentsCapexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights/variance': {
      id: '/_authenticated/insights/variance'
      path: '/insights/variance'
      fullPath: '/insights/variance'
      preLoaderRoute: typeof AuthenticatedInsightsVarianceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights/trends': {
      id: '/_authenticated/insights/trends'
      path: '/insights/trends'
      fullPath: '/insights/trends'
      preLoaderRoute: typeof AuthenticatedInsightsTrendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights/reports': {
      id: '/_authenticated/insights/reports'
      path: '/insights/reports'
      fullPath: '/insights/reports'
      preLoaderRoute: typeof AuthenticatedInsightsReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights/kpis': {
      id: '/_authenticated/insights/kpis'
      path: '/insights/kpis'
      fullPath: '/insights/kpis'
      preLoaderRoute: typeof AuthenticatedInsightsKpisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights/dashboards': {
      id: '/_authenticated/insights/dashboards'
      path: '/insights/dashboards'
      fullPath: '/insights/dashboards'
      preLoaderRoute: typeof AuthenticatedInsightsDashboardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/enrollment/validation': {
      id: '/_authenticated/enrollment/validation'
      path: '/enrollment/validation'
      fullPath: '/enrollment/validation'
      preLoaderRoute: typeof AuthenticatedEnrollmentValidationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/enrollment/settings': {
      id: '/_authenticated/enrollment/settings'
      path: '/enrollment/settings'
      fullPath: '/enrollment/settings'
      preLoaderRoute: typeof AuthenticatedEnrollmentSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/enrollment/projections': {
      id: '/_authenticated/enrollment/projections'
      path: '/enrollment/projections'
      fullPath: '/enrollment/projections'
      preLoaderRoute: typeof AuthenticatedEnrollmentProjectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/enrollment/class-structure': {
      id: '/_authenticated/enrollment/class-structure'
      path: '/enrollment/class-structure'
      fullPath: '/enrollment/class-structure'
      preLoaderRoute: typeof AuthenticatedEnrollmentClassStructureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs/settings': {
      id: '/_authenticated/costs/settings'
      path: '/costs/settings'
      fullPath: '/costs/settings'
      preLoaderRoute: typeof AuthenticatedCostsSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs/personnel': {
      id: '/_authenticated/costs/personnel'
      path: '/costs/personnel'
      fullPath: '/costs/personnel'
      preLoaderRoute: typeof AuthenticatedCostsPersonnelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs/overhead': {
      id: '/_authenticated/costs/overhead'
      path: '/costs/overhead'
      fullPath: '/costs/overhead'
      preLoaderRoute: typeof AuthenticatedCostsOverheadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs/operating': {
      id: '/_authenticated/costs/operating'
      path: '/costs/operating'
      fullPath: '/costs/operating'
      preLoaderRoute: typeof AuthenticatedCostsOperatingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consolidation/statements': {
      id: '/_authenticated/consolidation/statements'
      path: '/consolidation/statements'
      fullPath: '/consolidation/statements'
      preLoaderRoute: typeof AuthenticatedConsolidationStatementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consolidation/rollup': {
      id: '/_authenticated/consolidation/rollup'
      path: '/consolidation/rollup'
      fullPath: '/consolidation/rollup'
      preLoaderRoute: typeof AuthenticatedConsolidationRollupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consolidation/exports': {
      id: '/_authenticated/consolidation/exports'
      path: '/consolidation/exports'
      fullPath: '/consolidation/exports'
      preLoaderRoute: typeof AuthenticatedConsolidationExportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consolidation/checklist': {
      id: '/_authenticated/consolidation/checklist'
      path: '/consolidation/checklist'
      fullPath: '/consolidation/checklist'
      preLoaderRoute: typeof AuthenticatedConsolidationChecklistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/uploads': {
      id: '/_authenticated/admin/uploads'
      path: '/admin/uploads'
      fullPath: '/admin/uploads'
      preLoaderRoute: typeof AuthenticatedAdminUploadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/historical-import': {
      id: '/_authenticated/admin/historical-import'
      path: '/admin/historical-import'
      fullPath: '/admin/historical-import'
      preLoaderRoute: typeof AuthenticatedAdminHistoricalImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workforce/settings/timetable': {
      id: '/_authenticated/workforce/settings/timetable'
      path: '/timetable'
      fullPath: '/workforce/settings/timetable'
      preLoaderRoute: typeof AuthenticatedWorkforceSettingsTimetableRouteImport
      parentRoute: typeof AuthenticatedWorkforceSettingsRoute
    }
    '/_authenticated/workforce/settings/subject-hours': {
      id: '/_authenticated/workforce/settings/subject-hours'
      path: '/subject-hours'
      fullPath: '/workforce/settings/subject-hours'
      preLoaderRoute: typeof AuthenticatedWorkforceSettingsSubjectHoursRouteImport
      parentRoute: typeof AuthenticatedWorkforceSettingsRoute
    }
    '/_authenticated/workforce/settings/hsa-rates': {
      id: '/_authenticated/workforce/settings/hsa-rates'
      path: '/hsa-rates'
      fullPath: '/workforce/settings/hsa-rates'
      preLoaderRoute: typeof AuthenticatedWorkforceSettingsHsaRatesRouteImport
      parentRoute: typeof AuthenticatedWorkforceSettingsRoute
    }
    '/_authenticated/workforce/settings/cost-parameters': {
      id: '/_authenticated/workforce/settings/cost-parameters'
      path: '/cost-parameters'
      fullPath: '/workforce/settings/cost-parameters'
      preLoaderRoute: typeof AuthenticatedWorkforceSettingsCostParametersRouteImport
      parentRoute: typeof AuthenticatedWorkforceSettingsRoute
    }
  }
}

interface AuthenticatedWorkforceSettingsRouteChildren {
  AuthenticatedWorkforceSettingsCostParametersRoute: typeof AuthenticatedWorkforceSettingsCostParametersRoute
  AuthenticatedWorkforceSettingsHsaRatesRoute: typeof AuthenticatedWorkforceSettingsHsaRatesRoute
  AuthenticatedWorkforceSettingsSubjectHoursRoute: typeof AuthenticatedWorkforceSettingsSubjectHoursRoute
  AuthenticatedWorkforceSettingsTimetableRoute: typeof AuthenticatedWorkforceSettingsTimetableRoute
}

const AuthenticatedWorkforceSettingsRouteChildren: AuthenticatedWorkforceSettingsRouteChildren =
  {
    AuthenticatedWorkforceSettingsCostParametersRoute:
      AuthenticatedWorkforceSettingsCostParametersRoute,
    AuthenticatedWorkforceSettingsHsaRatesRoute:
      AuthenticatedWorkforceSettingsHsaRatesRoute,
    AuthenticatedWorkforceSettingsSubjectHoursRoute:
      AuthenticatedWorkforceSettingsSubjectHoursRoute,
    AuthenticatedWorkforceSettingsTimetableRoute:
      AuthenticatedWorkforceSettingsTimetableRoute,
  }

const AuthenticatedWorkforceSettingsRouteWithChildren =
  AuthenticatedWorkforceSettingsRoute._addFileChildren(
    AuthenticatedWorkforceSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminHistoricalImportRoute: typeof AuthenticatedAdminHistoricalImportRoute
  AuthenticatedAdminUploadsRoute: typeof AuthenticatedAdminUploadsRoute
  AuthenticatedConsolidationChecklistRoute: typeof AuthenticatedConsolidationChecklistRoute
  AuthenticatedConsolidationExportsRoute: typeof AuthenticatedConsolidationExportsRoute
  AuthenticatedConsolidationRollupRoute: typeof AuthenticatedConsolidationRollupRoute
  AuthenticatedConsolidationStatementsRoute: typeof AuthenticatedConsolidationStatementsRoute
  AuthenticatedCostsOperatingRoute: typeof AuthenticatedCostsOperatingRoute
  AuthenticatedCostsOverheadRoute: typeof AuthenticatedCostsOverheadRoute
  AuthenticatedCostsPersonnelRoute: typeof AuthenticatedCostsPersonnelRoute
  AuthenticatedCostsSettingsRoute: typeof AuthenticatedCostsSettingsRoute
  AuthenticatedEnrollmentClassStructureRoute: typeof AuthenticatedEnrollmentClassStructureRoute
  AuthenticatedEnrollmentProjectionsRoute: typeof AuthenticatedEnrollmentProjectionsRoute
  AuthenticatedEnrollmentSettingsRoute: typeof AuthenticatedEnrollmentSettingsRoute
  AuthenticatedEnrollmentValidationRoute: typeof AuthenticatedEnrollmentValidationRoute
  AuthenticatedInsightsDashboardsRoute: typeof AuthenticatedInsightsDashboardsRoute
  AuthenticatedInsightsKpisRoute: typeof AuthenticatedInsightsKpisRoute
  AuthenticatedInsightsReportsRoute: typeof AuthenticatedInsightsReportsRoute
  AuthenticatedInsightsTrendsRoute: typeof AuthenticatedInsightsTrendsRoute
  AuthenticatedInsightsVarianceRoute: typeof AuthenticatedInsightsVarianceRoute
  AuthenticatedInvestmentsCapexRoute: typeof AuthenticatedInvestmentsCapexRoute
  AuthenticatedInvestmentsCashflowRoute: typeof AuthenticatedInvestmentsCashflowRoute
  AuthenticatedInvestmentsProjectsRoute: typeof AuthenticatedInvestmentsProjectsRoute
  AuthenticatedInvestmentsSettingsRoute: typeof AuthenticatedInvestmentsSettingsRoute
  AuthenticatedRevenueOtherRoute: typeof AuthenticatedRevenueOtherRoute
  AuthenticatedRevenueSettingsRoute: typeof AuthenticatedRevenueSettingsRoute
  AuthenticatedRevenueSubsidiesRoute: typeof AuthenticatedRevenueSubsidiesRoute
  AuthenticatedRevenueTuitionRoute: typeof AuthenticatedRevenueTuitionRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedSettingsVersionsRoute: typeof AuthenticatedSettingsVersionsRoute
  AuthenticatedStrategicLongTermRoute: typeof AuthenticatedStrategicLongTermRoute
  AuthenticatedStrategicScenariosRoute: typeof AuthenticatedStrategicScenariosRoute
  AuthenticatedStrategicTargetsRoute: typeof AuthenticatedStrategicTargetsRoute
  AuthenticatedWorkforceAefePositionsRoute: typeof AuthenticatedWorkforceAefePositionsRoute
  AuthenticatedWorkforceDhgRoute: typeof AuthenticatedWorkforceDhgRoute
  AuthenticatedWorkforceEmployeesRoute: typeof AuthenticatedWorkforceEmployeesRoute
  AuthenticatedWorkforceGapAnalysisRoute: typeof AuthenticatedWorkforceGapAnalysisRoute
  AuthenticatedWorkforceRequirementsRoute: typeof AuthenticatedWorkforceRequirementsRoute
  AuthenticatedWorkforceSalariesRoute: typeof AuthenticatedWorkforceSalariesRoute
  AuthenticatedWorkforceSettingsRoute: typeof AuthenticatedWorkforceSettingsRouteWithChildren
  AuthenticatedConsolidationIndexRoute: typeof AuthenticatedConsolidationIndexRoute
  AuthenticatedCostsIndexRoute: typeof AuthenticatedCostsIndexRoute
  AuthenticatedEnrollmentIndexRoute: typeof AuthenticatedEnrollmentIndexRoute
  AuthenticatedInsightsIndexRoute: typeof AuthenticatedInsightsIndexRoute
  AuthenticatedInvestmentsIndexRoute: typeof AuthenticatedInvestmentsIndexRoute
  AuthenticatedRevenueIndexRoute: typeof AuthenticatedRevenueIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedStrategicIndexRoute: typeof AuthenticatedStrategicIndexRoute
  AuthenticatedWorkforceIndexRoute: typeof AuthenticatedWorkforceIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminHistoricalImportRoute:
    AuthenticatedAdminHistoricalImportRoute,
  AuthenticatedAdminUploadsRoute: AuthenticatedAdminUploadsRoute,
  AuthenticatedConsolidationChecklistRoute:
    AuthenticatedConsolidationChecklistRoute,
  AuthenticatedConsolidationExportsRoute:
    AuthenticatedConsolidationExportsRoute,
  AuthenticatedConsolidationRollupRoute: AuthenticatedConsolidationRollupRoute,
  AuthenticatedConsolidationStatementsRoute:
    AuthenticatedConsolidationStatementsRoute,
  AuthenticatedCostsOperatingRoute: AuthenticatedCostsOperatingRoute,
  AuthenticatedCostsOverheadRoute: AuthenticatedCostsOverheadRoute,
  AuthenticatedCostsPersonnelRoute: AuthenticatedCostsPersonnelRoute,
  AuthenticatedCostsSettingsRoute: AuthenticatedCostsSettingsRoute,
  AuthenticatedEnrollmentClassStructureRoute:
    AuthenticatedEnrollmentClassStructureRoute,
  AuthenticatedEnrollmentProjectionsRoute:
    AuthenticatedEnrollmentProjectionsRoute,
  AuthenticatedEnrollmentSettingsRoute: AuthenticatedEnrollmentSettingsRoute,
  AuthenticatedEnrollmentValidationRoute:
    AuthenticatedEnrollmentValidationRoute,
  AuthenticatedInsightsDashboardsRoute: AuthenticatedInsightsDashboardsRoute,
  AuthenticatedInsightsKpisRoute: AuthenticatedInsightsKpisRoute,
  AuthenticatedInsightsReportsRoute: AuthenticatedInsightsReportsRoute,
  AuthenticatedInsightsTrendsRoute: AuthenticatedInsightsTrendsRoute,
  AuthenticatedInsightsVarianceRoute: AuthenticatedInsightsVarianceRoute,
  AuthenticatedInvestmentsCapexRoute: AuthenticatedInvestmentsCapexRoute,
  AuthenticatedInvestmentsCashflowRoute: AuthenticatedInvestmentsCashflowRoute,
  AuthenticatedInvestmentsProjectsRoute: AuthenticatedInvestmentsProjectsRoute,
  AuthenticatedInvestmentsSettingsRoute: AuthenticatedInvestmentsSettingsRoute,
  AuthenticatedRevenueOtherRoute: AuthenticatedRevenueOtherRoute,
  AuthenticatedRevenueSettingsRoute: AuthenticatedRevenueSettingsRoute,
  AuthenticatedRevenueSubsidiesRoute: AuthenticatedRevenueSubsidiesRoute,
  AuthenticatedRevenueTuitionRoute: AuthenticatedRevenueTuitionRoute,
  AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
  AuthenticatedSettingsVersionsRoute: AuthenticatedSettingsVersionsRoute,
  AuthenticatedStrategicLongTermRoute: AuthenticatedStrategicLongTermRoute,
  AuthenticatedStrategicScenariosRoute: AuthenticatedStrategicScenariosRoute,
  AuthenticatedStrategicTargetsRoute: AuthenticatedStrategicTargetsRoute,
  AuthenticatedWorkforceAefePositionsRoute:
    AuthenticatedWorkforceAefePositionsRoute,
  AuthenticatedWorkforceDhgRoute: AuthenticatedWorkforceDhgRoute,
  AuthenticatedWorkforceEmployeesRoute: AuthenticatedWorkforceEmployeesRoute,
  AuthenticatedWorkforceGapAnalysisRoute:
    AuthenticatedWorkforceGapAnalysisRoute,
  AuthenticatedWorkforceRequirementsRoute:
    AuthenticatedWorkforceRequirementsRoute,
  AuthenticatedWorkforceSalariesRoute: AuthenticatedWorkforceSalariesRoute,
  AuthenticatedWorkforceSettingsRoute:
    AuthenticatedWorkforceSettingsRouteWithChildren,
  AuthenticatedConsolidationIndexRoute: AuthenticatedConsolidationIndexRoute,
  AuthenticatedCostsIndexRoute: AuthenticatedCostsIndexRoute,
  AuthenticatedEnrollmentIndexRoute: AuthenticatedEnrollmentIndexRoute,
  AuthenticatedInsightsIndexRoute: AuthenticatedInsightsIndexRoute,
  AuthenticatedInvestmentsIndexRoute: AuthenticatedInvestmentsIndexRoute,
  AuthenticatedRevenueIndexRoute: AuthenticatedRevenueIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedStrategicIndexRoute: AuthenticatedStrategicIndexRoute,
  AuthenticatedWorkforceIndexRoute: AuthenticatedWorkforceIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
